language: python
os:
  - linux
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install pycodestyle pytest codecov
  - pip install .
script:
  - pytest
  - find . -name "*.py" -exec pycodestyle --ignore E501,W503 {} +

after_succes:
  - codecov
