language: python
os:
  - linux
dist:
  - xenial
python:
  - 3.6
  - 3.7
  - 3.8-dev  # tests fail on 3.8.0 (default), but succeed on 3.8.5
install:
  - pip install pycodestyle pytest pytest-cov codecov
  - pip install .
script:
  - pytest
  - find . -name "*.py" -exec pycodestyle --ignore E501,W503 {} +
after_success:
  - codecov
