language: python
os:
  - linux
dist:
  - xenial
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install pycodestyle pytest pytest-cov codecov
  - pip install .
script:
  - pytest
  - find . -name "*.py" -exec pycodestyle --ignore E501,W503 {} +
after_success:
  - codecov

jobs:
    # allow python 3.8 to fail until we figure out why tests fail on 3.8
    allow_failures:
      - python: 3.8
